version: '3'
services:
  gs-database:
    image: "cassandra:latest"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      - _JAVA_OPTIONS="-Xmx6g"
    volumes:
      - $DATA_PATH/cassandra_data:/var/lib/cassandra
        #   - $DATA_PATH/cassandra_etc/cassandra.yaml:/etc/cassandra/cassandra.yaml

  gs-blocksci:
    image: "blocksci:latest"
    build:
            context: $DOWNLOAD_PATH/graphsense-blocksci
            dockerfile: $DOWNLOAD_PATH/graphsense-blocksci/Dockerfile
    volumes:
      - $DATA_PATH/btc-client-data:/var/data/block_data
      - $DATA_PATH/blocksci_data:/var/data/blocksci_data
      - $DOWNLOAD_PATH/graphsense-blocksci:/graphsense-blocksci
    command: tail -f /dev/null

  gs-bitcoin:
    image: "graphsense-bitcoin:latest"
    build:
        context: $DOWNLOAD_PATH/graphsense-btc-client
        dockerfile: Dockerfile
    volumes:
        - $DATA_PATH/btc-client-data:/opt/graphsense/data
    ports:
        - "8332:8332"
            #command: tail -f /dev/null
    command: bitcoind -conf=/opt/graphsense/bitcoin.conf -datadir=/opt/graphsense/data -rest
        #    restart: always

  gs-glue:
    image: "graphsense-glue:latest"
    build:
      context: $DOWNLOAD_PATH/graphsense-glue
      dockerfile: $DOWNLOAD_PATH/graphsense-glue/Dockerfile
    volumes:
      - $DOWNLOAD_PATH/graphsense-blocksci:/graphsense-blocksci
      - $DOWNLOAD_PATH/graphsense-clustering:/graphsense-clustering
      - $DOWNLOAD_PATH/graphsense-transformation:/graphsense-transformation
      - $DOWNLOAD_PATH/graphsense-tagpacks:/graphsense-tagpacks
      - $DOWNLOAD_PATH/btc-client:/btc-client
      - $DATA_PATH/btc-client-data:/btc-client-data
      - $DATA_PATH/blocksci_data:/blocksci_data
    ports:
      - "4040:4040"
      - "8080:8080"
    environment:
      - _JAVA_OPTIONS="-Xmx12g"
    command: tail -f /dev/null

  gs-rest:
    image: "graphsense-rest:latest"
    build:
        context: $DOWNLOAD_PATH/graphsense-rest
        dockerfile: Dockerfile
        args:
          rest_user: $REST_USER
          rest_passwd: $REST_PASSWD
    #    volumes: 
    #  -
    ports:
      - "9000:9000"
    depends_on:
      - "gs-database"

  gs-dashboard:
    image: "graphsense-dashboard:latest"
    build:
        context: $DOWNLOAD_PATH/graphsense-dashboard
        dockerfile: Dockerfile
    environment:
            - REST_ENDPOINT=$REST_ENDPOINT
            - JWT_TOKEN=$JWT_TOKEN
    env_file:
      - $DATA_PATH/gs-rest/JWT_TOKEN
    ports:
      - "8000:80"
    depends_on:
      - "gs-rest"

