version: '3'
services:
  cassandra:
    image: "cassandra:latest"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      - _JAVA_OPTIONS="-Xmx12g"
    volumes:
      - /mnt/graphsensevol/cassandra_data:/var/lib/cassandra
      - /mnt/graphsensevol/cassandra_etc/cassandra.yaml:/etc/cassandra/cassandra.yaml

  gs-blocksci:
    image: "blocksci:latest"
    volumes:
      - /mnt/graphsensevol/btc-client-data:/var/data/block_data
      - /mnt/graphsensevol/blocksci_data:/var/data/blocksci_data
      - /mnt/graphsensevol/graphsense-blocksci:/graphsense-blocksci
    command: tail -f /dev/null

    #  gs-bitcoin:
    #    image: "graphsense-bitcoin:latest"
    #    volumes:
    #      - /mnt/graphsensevol/btc-client-data:/opt/graphsense/data
    #    ports:
    #      - "8332:8332"
    #        #command: tail -f /dev/null
    #    command: bitcoind -conf=/opt/graphsense/bitcoin.conf -datadir=/opt/graphsense/data -rest
    #    restart: always

  gs-glue:
    image: "graphsense-glue:latest"
    volumes:
      - /mnt/graphsensevol/graphsense-blocksci:/graphsense-blocksci
      - /mnt/graphsensevol/graphsense-clustering:/graphsense-clustering
      - /mnt/graphsensevol/graphsense-transformation:/graphsense-transformation
      - /mnt/graphsensevol/graphsense-tagpacks:/graphsense-tagpacks
      - /mnt/graphsensevol/btc-client:/btc-client
      - /mnt/graphsensevol/btc-client-data:/btc-client-data
      - /mnt/graphsensevol/blocksci_data:/blocksci_data
    ports:
      - "4040:4040"
      - "8080:8080"
    environment:
      - _JAVA_OPTIONS="-Xmx12g"
    command: tail -f /dev/null

  gs-rest:
    image: "graphsense-rest:latest"
    #    volumes: 
    #  -
    ports:
      - "9000:9000"
    depends_on:
      - "cassandra"

  gs-dashboard:
    image: "graphsense-dashboard:latest"
    environment:
            - REST_ENDPOINT=http://172.16.63.126:9000
            - JWT_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NjQ2MjQxMDEsIm5iZiI6MTU2NDYyNDEwMSwianRpIjoiMjhiOWExMjEtNDBjZi00MTg5LTk0ODAtYmI0MmFmNDRmMTY0IiwiaWRlbnRpdHkiOiJhZG1pbiIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.OSyRWD8CZuF6Q86-ZF9wthm6NnX6jhI3sU09HACgKiI
    ports:
      - "8000:80"
    depends_on:
      - "gs-rest"

